export {default as Topbar } from './global/Topbar'
export {default as Sidebar} from './global/Sidebar'
export {default as Dashboard} from './dashboard/Dashboard'
export {default as Team} from './team/Team'
// export {default as Invoices } from './scenes/invoices'
// export {default as Contacts } from './scenes/contacts'
// export {default as Bar } from './scenes/bar'
// export {default as Form } from './scenes/form'
// export {default as Line } from './scenes/line'
// export {default as Pie } from './scenes/pie'
// export {default as FAQ } from './scenes/faq'
// export {default as Geography } from './scenes/geography'
// export {default as Calender } from './scenes/calender'
